[global]
   workgroup = WORKGROUP
   server string = ULSA Local-Hub Server
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   map to guest = bad user

[hub-compartido]
   path = /srv/samba/hub
   browseable = yes
   writeable = yes
   guest ok = no
   valid users = importar
   create mask = 0775
   directory mask = 0775
