[global]
   workgroup = WORKGROUP
   server string = ChatoSync Hub Server
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   map to guest = bad user

[hub]
   path = /srv/samba/hub
   browseable = yes
   writeable = yes
   guest ok = yes
   read only = no
   create mask = 0777
   directory mask = 0777

[hub-compartido]
   path = /srv/samba/hub
   browseable = yes
   writeable = yes
   guest ok = yes
   read only = no
   create mask = 0777
   directory mask = 0777
